2018-05-30 07:13:48  [ main:0 ] - [ DEBUG ]  Using Log4J as the default logging framework
2018-05-30 07:13:48  [ main:8 ] - [ DEBUG ]  java.nio.Buffer.address: available
2018-05-30 07:13:48  [ main:8 ] - [ DEBUG ]  sun.misc.Unsafe.theUnsafe: available
2018-05-30 07:13:48  [ main:10 ] - [ DEBUG ]  sun.misc.Unsafe.copyMemory: available
2018-05-30 07:13:48  [ main:11 ] - [ DEBUG ]  java.nio.Bits.unaligned: true
2018-05-30 07:13:48  [ main:12 ] - [ DEBUG ]  Platform: Windows
2018-05-30 07:13:48  [ main:13 ] - [ DEBUG ]  Java version: 7
2018-05-30 07:13:48  [ main:13 ] - [ DEBUG ]  -Dio.netty.noUnsafe: false
2018-05-30 07:13:48  [ main:14 ] - [ DEBUG ]  sun.misc.Unsafe: available
2018-05-30 07:13:48  [ main:14 ] - [ DEBUG ]  -Dio.netty.noJavassist: false
2018-05-30 07:13:48  [ main:88 ] - [ DEBUG ]  Javassist: available
2018-05-30 07:13:48  [ main:89 ] - [ DEBUG ]  -Dio.netty.tmpdir: C:\Users\tlju-pc\AppData\Local\Temp (java.io.tmpdir)
2018-05-30 07:13:48  [ main:89 ] - [ DEBUG ]  -Dio.netty.bitMode: 32 (sun.arch.data.model)
2018-05-30 07:13:48  [ main:89 ] - [ DEBUG ]  -Dio.netty.noPreferDirect: false
2018-05-30 07:13:48  [ main:102 ] - [ DEBUG ]  -Dio.netty.leakDetectionLevel: simple
2018-05-30 07:13:48  [ main:121 ] - [ DEBUG ]  -Dio.netty.eventLoopThreads: 16
2018-05-30 07:13:48  [ main:137 ] - [ DEBUG ]  -Dio.netty.noKeySetOptimization: false
2018-05-30 07:13:48  [ main:137 ] - [ DEBUG ]  -Dio.netty.selectorAutoRebuildThreshold: 512
2018-05-30 07:13:48  [ main:197 ] - [ INFO ]  Start to create connection to 10.150.68.133:60001 for channel :10.150.68.133:60001::0.
2018-05-30 07:13:50  [ main:2219 ] - [ DEBUG ]  -Dio.netty.initialSeedUniquifier: 0xcdabe37660ce52eb (took 2010 ms)
2018-05-30 07:13:50  [ main:2247 ] - [ DEBUG ]  -Dio.netty.allocator.type: unpooled
2018-05-30 07:13:50  [ main:2248 ] - [ DEBUG ]  -Dio.netty.threadLocalDirectBufferSize: 65536
2018-05-30 07:13:50  [ NettyTransceiver-eventLoopGroup 1:2260 ] - [ DEBUG ]  Generated: io.netty.util.internal.__matchers__.com.csg.itms.edic.util.protocol.ProtocolPackMatcher
2018-05-30 07:13:53  [ NettyTransceiver-eventLoopGroup 1:4572 ] - [ WARN ]  Channel :10.150.68.133:60001::0 is ungreistered with null from local address :null
2018-05-30 07:13:53  [ main:4572 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:248)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)
Caused by: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-30 07:13:53  [ main:4573 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: channel is null.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:250)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)

2018-05-30 07:13:53  [ main:4573 ] - [ ERROR ]  Error happened in authenticate process, caused by java.io.IOException: channel is null.
2018-05-30 07:13:53  [ main:4585 ] - [ INFO ]  Start to create connection to 10.150.68.133:60001 for channel :10.150.68.133:60001::0.
2018-05-30 07:13:54  [ NettyTransceiver-eventLoopGroup 2:6311 ] - [ WARN ]  Channel :10.150.68.133:60001::0 is ungreistered with null from local address :null
2018-05-30 07:13:54  [ main:6312 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:280)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-30 07:13:54  [ main:6313 ] - [ ERROR ]  There is no netty channel can be send the message.
2018-05-30 07:13:54  [ main:6313 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)

2018-05-30 07:13:54  [ main:6314 ] - [ ERROR ]  Error happened in sendMessage, caused by java.util.concurrent.ExecutionException: java.io.IOException: There is no netty channel can be send the message.
	at org.apache.avro.ipc.CallFuture.get(CallFuture.java:118)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:80)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	... 1 more

2018-05-30 07:14:18  [ EDIClient Scheduler 1:30174 ] - [ INFO ]  No¡£=1 SubjectName=SOA2NARIAlertSend   Current RPS=0   Avg RPS=0  Success Request=0  Total Request=1  Failure Request=1
2018-05-30 07:14:18  [ pool-1-thread-1:30295 ] - [ ERROR ]  Error happened in CallbackTimeoutDecorate, for the -2147483648's data package.
2018-05-30 07:14:23  [ pool-1-thread-1:34596 ] - [ ERROR ]  Error happened in CallbackTimeoutDecorate, for the -2147483647's data package.
2018-05-30 07:14:55  [ main:66459 ] - [ INFO ]  Start to create connection to 10.150.68.133:60001 for channel :10.150.68.133:60001::0.
2018-05-30 07:14:57  [ NettyTransceiver-eventLoopGroup 3:68606 ] - [ WARN ]  Channel :10.150.68.133:60001::0 is ungreistered with null from local address :null
2018-05-30 07:14:57  [ main:68606 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:248)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)
Caused by: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-30 07:14:57  [ main:68607 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: channel is null.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:250)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)

2018-05-30 07:14:57  [ main:68607 ] - [ ERROR ]  Error happened in authenticate process, caused by java.io.IOException: channel is null.
2018-05-30 07:14:57  [ main:68609 ] - [ INFO ]  Start to create connection to 10.150.68.133:60001 for channel :10.150.68.133:60001::0.
2018-05-30 07:14:58  [ NettyTransceiver-eventLoopGroup 4:70187 ] - [ WARN ]  Channel :10.150.68.133:60001::0 is ungreistered with null from local address :null
2018-05-30 07:14:58  [ main:70187 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:280)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-30 07:14:58  [ main:70188 ] - [ ERROR ]  There is no netty channel can be send the message.
2018-05-30 07:14:58  [ main:70188 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)

2018-05-30 07:14:58  [ main:70189 ] - [ ERROR ]  Error happened in sendMessage, caused by java.util.concurrent.ExecutionException: java.io.IOException: There is no netty channel can be send the message.
	at org.apache.avro.ipc.CallFuture.get(CallFuture.java:118)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:80)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	... 1 more

2018-05-30 09:45:33  [ main:0 ] - [ DEBUG ]  Using Log4J as the default logging framework
2018-05-30 09:45:33  [ main:56 ] - [ DEBUG ]  java.nio.Buffer.address: available
2018-05-30 09:45:33  [ main:57 ] - [ DEBUG ]  sun.misc.Unsafe.theUnsafe: available
2018-05-30 09:45:33  [ main:81 ] - [ DEBUG ]  sun.misc.Unsafe.copyMemory: available
2018-05-30 09:45:33  [ main:83 ] - [ DEBUG ]  java.nio.Bits.unaligned: true
2018-05-30 09:45:33  [ main:86 ] - [ DEBUG ]  Platform: Windows
2018-05-30 09:45:33  [ main:89 ] - [ DEBUG ]  Java version: 7
2018-05-30 09:45:33  [ main:89 ] - [ DEBUG ]  -Dio.netty.noUnsafe: false
2018-05-30 09:45:33  [ main:90 ] - [ DEBUG ]  sun.misc.Unsafe: available
2018-05-30 09:45:33  [ main:91 ] - [ DEBUG ]  -Dio.netty.noJavassist: false
2018-05-30 09:45:33  [ main:182 ] - [ DEBUG ]  Javassist: available
2018-05-30 09:45:33  [ main:183 ] - [ DEBUG ]  -Dio.netty.tmpdir: C:\Users\tlju-pc\AppData\Local\Temp (java.io.tmpdir)
2018-05-30 09:45:33  [ main:183 ] - [ DEBUG ]  -Dio.netty.bitMode: 32 (sun.arch.data.model)
2018-05-30 09:45:33  [ main:184 ] - [ DEBUG ]  -Dio.netty.noPreferDirect: false
2018-05-30 09:45:33  [ main:278 ] - [ DEBUG ]  -Dio.netty.leakDetectionLevel: simple
2018-05-30 09:45:33  [ main:336 ] - [ DEBUG ]  -Dio.netty.eventLoopThreads: 16
2018-05-30 09:45:33  [ main:466 ] - [ DEBUG ]  -Dio.netty.noKeySetOptimization: false
2018-05-30 09:45:33  [ main:468 ] - [ DEBUG ]  -Dio.netty.selectorAutoRebuildThreshold: 512
2018-05-30 09:45:33  [ main:678 ] - [ INFO ]  Start to create connection to 10.150.68.133:60001 for channel :10.150.68.133:60001::0.
2018-05-30 09:45:36  [ main:2759 ] - [ DEBUG ]  -Dio.netty.initialSeedUniquifier: 0xc2319540acd0703c (took 2069 ms)
2018-05-30 09:45:36  [ main:2899 ] - [ DEBUG ]  -Dio.netty.allocator.type: unpooled
2018-05-30 09:45:36  [ main:2899 ] - [ DEBUG ]  -Dio.netty.threadLocalDirectBufferSize: 65536
2018-05-30 09:45:36  [ NettyTransceiver-eventLoopGroup 1:2930 ] - [ DEBUG ]  Generated: io.netty.util.internal.__matchers__.com.csg.itms.edic.util.protocol.ProtocolPackMatcher
2018-05-30 09:45:57  [ NettyTransceiver-eventLoopGroup 1:23942 ] - [ WARN ]  Channel :10.150.68.133:60001::0 is ungreistered with null from local address :null
2018-05-30 09:45:57  [ main:23943 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection timed out: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:248)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)
Caused by: java.net.ConnectException: Connection timed out: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-30 09:45:57  [ main:23946 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: channel is null.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:250)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)

2018-05-30 09:45:57  [ main:23948 ] - [ ERROR ]  Error happened in authenticate process, caused by java.io.IOException: channel is null.
2018-05-30 09:45:57  [ main:24063 ] - [ INFO ]  Start to create connection to 10.150.68.133:60001 for channel :10.150.68.133:60001::0.
2018-05-30 09:46:04  [ pool-1-thread-1:30777 ] - [ ERROR ]  Error happened in CallbackTimeoutDecorate, for the -2147483648's data package.
2018-05-30 09:46:18  [ NettyTransceiver-eventLoopGroup 2:45068 ] - [ WARN ]  Channel :10.150.68.133:60001::0 is ungreistered with null from local address :null
2018-05-30 09:46:18  [ main:45068 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection timed out: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:280)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.net.ConnectException: Connection timed out: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-30 09:46:18  [ main:45069 ] - [ ERROR ]  There is no netty channel can be send the message.
2018-05-30 09:46:18  [ EDIClient Scheduler 1:45068 ] - [ ERROR ]  Error happened in check channels.java.util.concurrent.ExecutionException: java.net.ConnectException: Connection timed out: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.client.EDIClient$MonitorRunable.run(EDIClient.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	... 1 more

2018-05-30 09:46:18  [ main:45069 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)

2018-05-30 09:46:18  [ EDIClient Scheduler 1:45073 ] - [ INFO ]  No¡£=1 SubjectName=SOA2NARIAlertSend   Current RPS=0   Avg RPS=0  Success Request=0  Total Request=1  Failure Request=0
2018-05-30 09:46:18  [ main:45073 ] - [ ERROR ]  Error happened in sendMessage, caused by java.util.concurrent.ExecutionException: java.io.IOException: There is no netty channel can be send the message.
	at org.apache.avro.ipc.CallFuture.get(CallFuture.java:118)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:80)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	... 1 more

2018-05-30 09:46:27  [ pool-1-thread-1:54077 ] - [ ERROR ]  Error happened in CallbackTimeoutDecorate, for the -2147483647's data package.
