2018-05-30 07:13:53  [ main:4572 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:248)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)
Caused by: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-30 07:13:53  [ main:4573 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: channel is null.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:250)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)

2018-05-30 07:13:53  [ main:4573 ] - [ ERROR ]  Error happened in authenticate process, caused by java.io.IOException: channel is null.
2018-05-30 07:13:54  [ main:6312 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:280)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-30 07:13:54  [ main:6313 ] - [ ERROR ]  There is no netty channel can be send the message.
2018-05-30 07:13:54  [ main:6313 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)

2018-05-30 07:13:54  [ main:6314 ] - [ ERROR ]  Error happened in sendMessage, caused by java.util.concurrent.ExecutionException: java.io.IOException: There is no netty channel can be send the message.
	at org.apache.avro.ipc.CallFuture.get(CallFuture.java:118)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:80)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	... 1 more

2018-05-30 07:14:18  [ pool-1-thread-1:30295 ] - [ ERROR ]  Error happened in CallbackTimeoutDecorate, for the -2147483648's data package.
2018-05-30 07:14:23  [ pool-1-thread-1:34596 ] - [ ERROR ]  Error happened in CallbackTimeoutDecorate, for the -2147483647's data package.
2018-05-30 07:14:57  [ main:68606 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:248)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)
Caused by: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-30 07:14:57  [ main:68607 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: channel is null.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:250)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)

2018-05-30 07:14:57  [ main:68607 ] - [ ERROR ]  Error happened in authenticate process, caused by java.io.IOException: channel is null.
2018-05-30 07:14:58  [ main:70187 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:280)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.net.ConnectException: Connection refused: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-30 07:14:58  [ main:70188 ] - [ ERROR ]  There is no netty channel can be send the message.
2018-05-30 07:14:58  [ main:70188 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)

2018-05-30 07:14:58  [ main:70189 ] - [ ERROR ]  Error happened in sendMessage, caused by java.util.concurrent.ExecutionException: java.io.IOException: There is no netty channel can be send the message.
	at org.apache.avro.ipc.CallFuture.get(CallFuture.java:118)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:80)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	... 1 more

2018-05-30 09:45:57  [ main:23943 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection timed out: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:248)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)
Caused by: java.net.ConnectException: Connection timed out: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-30 09:45:57  [ main:23946 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: channel is null.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:250)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.authenticate(EDIClient.java:130)

2018-05-30 09:45:57  [ main:23948 ] - [ ERROR ]  Error happened in authenticate process, caused by java.io.IOException: channel is null.
2018-05-30 09:46:04  [ pool-1-thread-1:30777 ] - [ ERROR ]  Error happened in CallbackTimeoutDecorate, for the -2147483648's data package.
2018-05-30 09:46:18  [ main:45068 ] - [ ERROR ]  Exception in get channel :java.util.concurrent.ExecutionException: java.net.ConnectException: Connection timed out: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.netty.AbstractChannelFactory.get(AbstractChannelFactory.java:96)
	at com.csg.itms.edic.util.netty.NettyTransceiver.getChannel(NettyTransceiver.java:343)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:280)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.net.ConnectException: Connection timed out: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

2018-05-30 09:46:18  [ main:45069 ] - [ ERROR ]  There is no netty channel can be send the message.
2018-05-30 09:46:18  [ EDIClient Scheduler 1:45068 ] - [ ERROR ]  Error happened in check channels.java.util.concurrent.ExecutionException: java.net.ConnectException: Connection timed out: no further information: /10.150.68.133:60001
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.csg.itms.edic.util.client.EDIClient$MonitorRunable.run(EDIClient.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: no further information: /10.150.68.133:60001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	... 1 more

2018-05-30 09:46:18  [ main:45069 ] - [ ERROR ]  Error happened when call invokeAsync of RPCClient , caused by java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)

2018-05-30 09:46:18  [ main:45073 ] - [ ERROR ]  Error happened in sendMessage, caused by java.util.concurrent.ExecutionException: java.io.IOException: There is no netty channel can be send the message.
	at org.apache.avro.ipc.CallFuture.get(CallFuture.java:118)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:80)
	at com.csg.itms.edic.util.client.EDIClient.sendMesssage(EDIClient.java:210)
Caused by: java.io.IOException: There is no netty channel can be send the message.
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeToChannel(NettyTransceiver.java:294)
	at com.csg.itms.edic.util.netty.NettyTransceiver.writeDataPack(NettyTransceiver.java:286)
	at com.csg.itms.edic.util.netty.NettyTransceiver.transceive(NettyTransceiver.java:233)
	at com.csg.itms.edic.util.client.RPCClient.invokeAsync(RPCClient.java:128)
	at com.csg.itms.edic.util.client.RPCClient.invokeSync(RPCClient.java:78)
	... 1 more

2018-05-30 09:46:27  [ pool-1-thread-1:54077 ] - [ ERROR ]  Error happened in CallbackTimeoutDecorate, for the -2147483647's data package.
